[2019-02-10 20:10:46,505] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Ingestion_from_S3 2015-07-24T00:00:00+00:00 [queued]>
[2019-02-10 20:10:46,506] {models.py:1359} INFO - Dependencies all met for <TaskInstance: Rescale.Ingestion_from_S3 2015-07-24T00:00:00+00:00 [queued]>
[2019-02-10 20:10:46,506] {models.py:1571} INFO - 
--------------------------------------------------------------------------------
Starting attempt 1 of 2
--------------------------------------------------------------------------------

[2019-02-10 20:10:46,515] {models.py:1593} INFO - Executing <Task(BashOperator): Ingestion_from_S3> on 2015-07-24T00:00:00+00:00
[2019-02-10 20:10:46,515] {base_task_runner.py:118} INFO - Running: ['bash', '-c', 'airflow run Rescale Ingestion_from_S3 2015-07-24T00:00:00+00:00 --job_id 165 --raw -sd DAGS_FOLDER/rs-pipeline1.py --cfg_path /tmp/tmprqjecchh']
[2019-02-10 20:10:47,043] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3 [2019-02-10 20:10:47,043] {__init__.py:51} INFO - Using executor SequentialExecutor
[2019-02-10 20:10:47,196] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3 [2019-02-10 20:10:47,196] {models.py:273} INFO - Filling up the DagBag from /home/ec2-user/airflow/dags/rs-pipeline1.py
[2019-02-10 20:10:47,208] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3 [2019-02-10 20:10:47,208] {cli.py:520} INFO - Running <TaskInstance: Rescale.Ingestion_from_S3 2015-07-24T00:00:00+00:00 [running]> on host ip-172-31-15-235.us-east-2.compute.internal
[2019-02-10 20:10:47,218] {bash_operator.py:77} INFO - Tmp dir root location: 
 /tmp
[2019-02-10 20:10:47,218] {bash_operator.py:86} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_ID=Rescale
AIRFLOW_CTX_TASK_ID=Ingestion_from_S3
AIRFLOW_CTX_EXECUTION_DATE=2015-07-24T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2015-07-24T00:00:00+00:00
[2019-02-10 20:10:47,219] {bash_operator.py:100} INFO - Temporary script location: /tmp/airflowtmpz3c_gz9c/Ingestion_from_S3u_u7jbnk
[2019-02-10 20:10:47,219] {bash_operator.py:110} INFO - Running command: python /home/ec2-user/get_s3data.py
[2019-02-10 20:10:47,222] {bash_operator.py:119} INFO - Output:
[2019-02-10 20:10:47,243] {bash_operator.py:123} INFO - python: can't open file '/home/ec2-user/get_s3data.py': [Errno 2] No such file or directory
[2019-02-10 20:10:47,245] {bash_operator.py:127} INFO - Command exited with return code 2
[2019-02-10 20:10:47,250] {models.py:1788} ERROR - Bash command failed
Traceback (most recent call last):
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
    raise AirflowException("Bash command failed")
airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 20:10:47,251] {models.py:1811} INFO - Marking task as UP_FOR_RETRY
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3 Traceback (most recent call last):
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/bin/airflow", line 32, in <module>
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     args.func(args)
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/cli.py", line 74, in wrapper
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     return f(*args, **kwargs)
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 526, in run
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     _run(args, dag, ti)
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/bin/cli.py", line 445, in _run
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     pool=args.pool,
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/utils/db.py", line 73, in wrapper
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     return func(*args, **kwargs)
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/models.py", line 1657, in _run_raw_task
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     result = task_copy.execute(context=context)
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3   File "/home/ec2-user/airflow/venv/lib/python3.7/site-packages/airflow/operators/bash_operator.py", line 131, in execute
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3     raise AirflowException("Bash command failed")
[2019-02-10 20:10:47,263] {base_task_runner.py:101} INFO - Job 165: Subtask Ingestion_from_S3 airflow.exceptions.AirflowException: Bash command failed
[2019-02-10 20:10:51,508] {logging_mixin.py:95} INFO - [2019-02-10 20:10:51,508] {jobs.py:2527} INFO - Task exited with return code 1
